#!/usr/bin/env python3
"""Generate an OpenSCAD data file of QR-code matrices from URLs.

The 3D models read the committed `qr_data.scad`, so CI/OpenSCAD never need a QR
library — this tool is only run by hand to (re)generate that data file when a
URL changes.

Usage:
    tools/qrgen.py --out donation-qr-stand/qr_data.scad \
        venmo=https://venmo.com/u/IamMrCupp \
        cashapp='https://cash.app/$IamMrCupp'

Each `name=url` pair becomes a `<name>_qr` variable: a list of rows of 0/1
(1 = dark module), row 0 = the TOP of the code. The bare code matrix is emitted
with no quiet zone — the .scad adds the quiet zone parametrically.

Requires `segno` (pure-Python, no PIL): pip install segno
"""
import argparse
import sys

try:
    import segno
except ImportError:
    sys.exit("error: segno not installed — run: pip install segno")


def matrix_for(url, error):
    qr = segno.make(url, error=error)
    rows = ["".join("1" if cell else "0" for cell in row) for row in qr.matrix]
    return qr, rows


def emit(name, url, rows):
    n = len(rows)
    out = [f"// {name}: {url}  ({n}x{n})", f"{name}_qr = ["]
    for i, row in enumerate(rows):
        cells = ",".join(row)
        comma = "," if i < n - 1 else ""
        out.append(f"  [{cells}]{comma}")
    out.append("];")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", required=True, help="output .scad path")
    ap.add_argument("--error", default="q", choices=list("lmqh"),
                    help="QR error-correction level (default: q = ~25%%)")
    ap.add_argument("pairs", nargs="+", metavar="name=url",
                    help="one or more name=url pairs to encode")
    args = ap.parse_args()

    blocks = []
    cmd = f"tools/qrgen.py --out {args.out} --error {args.error} " + " ".join(
        f"{p}" for p in args.pairs)
    header = [
        "// AUTO-GENERATED by tools/qrgen.py — DO NOT EDIT BY HAND.",
        f"// Regenerate: {cmd}",
        f"// QR error-correction level: {args.error.upper()}. 1 = dark, row 0 = top.",
        "",
    ]
    for pair in args.pairs:
        if "=" not in pair:
            sys.exit(f"error: expected name=url, got {pair!r}")
        name, url = pair.split("=", 1)
        qr, rows = matrix_for(url, args.error)
        print(f"{name}: version {qr.version}, {len(rows)}x{len(rows)}, EC={args.error.upper()}",
              file=sys.stderr)
        blocks.append(emit(name, url, rows))

    with open(args.out, "w") as fh:
        fh.write("\n".join(header) + "\n" + "\n\n".join(blocks) + "\n")
    print(f"wrote {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
